var folders = ['controllers', 'views', 'models', 'public'];
var files = [['index.js', '.gitignore', 'package.json'], [], [], [], []];
var projectData = [
    {
        'type': 'folder',
        'name': 'root',
        'path': '/',
        'children': [
            {
                'type': 'folder',
                'name': 'controllers',
                'path': '/controllers',
                'children': []
            },
            {
                'type': 'folder',
                'name': 'models',
                'path': '/models',
                'children': []
            },
            {
                'type': 'folder',
                'name': 'public',
                'path': '/public',
                'children': []
            },
            {
                'type': 'folder',
                'name': 'views',
                'path': '/views',
                'children': []
            }
        ]
    },
    {
        'type': 'file',
        'name': '.gitignore',
        'path': '/.gitignore',
        'contents': `
                    # Logs
                    logs
                    *.log
                    npm-debug.log*

                    # Runtime data
                    pids
                    *.pid
                    *.seed

                    # Directory for instrumented libs generated by jscoverage/JSCover
                    lib-cov

                    # Coverage directory used by tools like istanbul
                    coverage

                    # Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
                    .grunt

                    # node-waf configuration
                    .lock-wscript

                    # Compiled binary addons (http://nodejs.org/api/addons.html)
                    build/Release

                    # Dependency directories
                    node_modules
                    jspm_packages

                    # Optional npm cache directory
                    .npm

                    # Optional REPL history
                    .node_repl_history
                    `
    },
    {
        'type': 'file',
        'name': 'index.js',
        'path': '/index.js',
        'contents': ''
    },
    {
        'type': 'file',
        'name': 'package.json',
        'path': '/package.json',
        'contents': ''
    }
];

module.exports = ({
    getRequireStatement: function (val) {
        return "var " + val + " = require('" + val + "');";
    },
    populateDirectory: function (username) {
        return console.log(projectData);
    }
})

function createFile() {
    for (var i in files) {
        for (var j in files[i]) {

        }
    }
}